### PR TITLE
Add portfolio app of Basith P

### PR DESCRIPTION
**Pull request by Basith-P**

### CODE REVIEW

**Comment by adi-code22** [comment]
Can we have a screenshot of the Portfolio pushed along with the code?

**Comment by Basith-P** [comment]
Hello
I've put the screenshot in the assets/ui folder

**Comment by Basith-P** [comment]
> Can we have a screenshot of the Portfolio pushed along with the code?

Here is the screenshot

Screenshot_20210917-163758

**Comment by adi-code22** [comment]
Cool! Merged ✔

**Pull request merged**
